name = "favsong"
main = "src/index.js"
compatibility_date = "2024-01-11"
workers_dev = true

[[routes]]
pattern = "favsong.alyxia.dev"
zone_name = "alyxia.dev"
custom_domain = true

[[kv_namespaces]]
id = "55472ebfb040444194533a19062bede4"
binding = "EXAMPLE_TODOS"
