name = "favsong"
main = "src/index.ts"
compatibility_date = "2024-01-11"
workers_dev = true
node_compat = true

[[routes]]
pattern = "favsong.alyxia.dev"
zone_name = "alyxia.dev"
custom_domain = true

[[kv_namespaces]]
id = "68ea663c670b4b6fadb2434d228ce7fd"
binding = "FAVSONG_KV"
